### PR TITLE
Add Text rendering to 2D

### PR DESCRIPTION
**Pull request by rioki**

### CODE REVIEW

**Review by rioki-lgtm — APPROVED** [review]

**Comment by rioki** [comment]
LGTM

**Review by rioki — COMMENTED** [review]
LGTM

**Comment by rioki** [comment]
Note: This PR is abused to get the LGTM comment trigger working.

**Comment by rioki** [comment]
LGTM

**Comment by rioki** [comment]
LGTM

**Comment by rioki** [comment]
LGTM

**Comment by rioki** [comment]
This does not contain the token.

**Comment by rioki** [comment]
LGTM

**Pull request merged**
